### ISSUE TITLE
Add support for BOM metadata in v1.2 of the spec

### ISSUE THREAD

**Issue by stevespringett** [CycloneDX/cyclonedx-php-composer#14]
The BOM metadata portion should, at a minimum, contain the tool and version of the tool used to create the BOM. In this case, it will be the PHP Composer implementation.

I don't think composer will give us much more of anything else to put into bom metadata. But at a minimum, we should support the tools element.

**Comment by jkowalleck** [comment]
reasons for this issue:
this plugin utilizes [composer](https://getcomposer.org/).
even composer might have CVEs (see https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=composer+php)
therefore composer itself should be added as a component to SBOM somehow.

**Comment by jkowalleck** [comment]
example SBOM:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<bom xmlns="http://cyclonedx.org/schema/bom/1.2" serialNumber="urn:uuid:c27a0868-4385-41f7-8d14-5be843c5c14a" version="1">
  <metadata>
    <timestamp>...</timestamp>
    <tools>
      <tool>
        <vendor>CycloneDX</vendor>
        <name>cyclonedx-php-composer</name>
        <version>...</version>
        <hashes>
          <hash alg="MD5">...</hash>
        </hashes>
      </tool>
      <tool>
        <vendor>composer</vendor>
        <name>composer</name>
        <version>...</version>
        <hashes>
          <hash alg="MD5">...</hash>
        </hashes>
      </tool>
    </tools>
  </metadata>
  <!-- compoents -->
</bom>
```

**Comment by jkowalleck** [comment]
specs: https://cyclonedx.org/use-cases/#packaging-and-distribution
