### ISSUE TITLE
[LEGAL] change copyright holder to "OWASP Foundation"

### ISSUE THREAD

**Issue by jkowalleck** [CycloneDX/cyclonedx-php-composer#242]
current copyright holder is Steve Springett @stevespringett .

Even though i am the original author, I added this notice as it was the usual with the CycloneDX implementations back then.
Today, the @CycloneDX used to go with a copyright to OWASP.

**Proposal: change copyright holder to "OWASP Foundation.".**

**Comment by stevespringett** [comment]
Agreed.  Copyright should be transferred to the OWASP Foundation. Please make the necessary changes.
