### ISSUE TITLE
Add support for dependency graph introduced in v1.2 of the spec

### ISSUE THREAD

**Issue by coderpatros** [CycloneDX/cyclonedx-php-composer#5]
see https://cyclonedx.org/use-cases/#dependency-graph

**Comment by stevespringett** [comment]
The Laravel SBOM example will need to be updated to spec v1.2 once this ticket is complete.

**Comment by jkowalleck** [comment]
@coderpatros 

i am not too famliar wth the 1.2 specs.
could you help me find the "dependency graph" element in the [XSD](https://cyclonedx.org/schema/bom/1.2) and [JSON SCHEMA](https://cyclonedx.org/schema/bom-1.2.schema.json) ?

**Comment by coderpatros** [comment]
@jkowalleck it’s at the BOM level https://cyclonedx.org/docs/1.2/#type_dependenciesType

**Comment by jkowalleck** [comment]
> The Laravel SBOM example will need to be updated to spec v1.2 once this ticket is complete.

see https://github.com/CycloneDX/sbom-examples/tree/master/laravel-7.12.0
(related: #58 )

**Comment by jkowalleck** [comment]
some notes:
* concept
  * the dependencies must not include dev-dependencies of any php-package
* data modelling
  1. the generator fills _all_ known dependencies as `A`
  1. for each `B` in `A`:  
      for each dependency `C` of `B`:  
      add item `D` from A that represents `C` as a dependency of  `B`.
* writing the dependencies to XML:
  for each `B` in `A`: 
  write `B`'s packageURL as `purl`
  for each `C` in `B`'s  dependencies:  
  write `C`'s packageURL(=purl) as `component`

**Comment by jkowalleck** [comment]
attention. keep alias packages in mind and how they should be handled.

**Comment by jkowalleck** [comment]
implementation aids: 
`composer why`  might have a dep tree implemented
`composer show --locked --tree` displays a dep tree - so it must utilize some tree maker somehow.
see if composers tree makers are public(non-internal) and can me used as a library.
