### ISSUE TITLE
Modify the generated package URL to match purl-spec

### ISSUE THREAD

**Issue by Szasza** [CycloneDX/cyclonedx-php-composer#6]
As per https://github.com/package-url/purl-spec a package URL is as follows:

```
scheme:type/namespace/name@version?qualifiers#subpath
```
This package generates URLs such as `pkg://composer/...` which don't follow the specification, the `//` part needs to be removed.

**Comment by Szasza** [comment]
@coderpatros thank you again for the merge.

I would like to ask if a v1.0.1 release can be created from this package, or shall I use `dev-master` as a dependency.

Thank you for your insight, it is much appreciated.

**Comment by coderpatros** [comment]
@Szasza I'll leave this issue open until it's released. If this is holding you up and you can use `dev-master` in the meantime that would be good. 

I've released I need to set up a release workflow for this implementation. So it might not be released straight away.

**Comment by Szasza** [comment]
@coderpatros no problem at the slightest.

Thank you again for the ultra-quick turnaround time, I will proceed with `dev-master` for now.

**Comment by coderpatros** [comment]
@Szasza this has now been released in v1.0.1

Thanks again for the PR!

**Comment by Szasza** [comment]
@coderpatros awesome, my pleasure! Thank you again for both the review and for the release, it is greatly appreciated.
